import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {evaluateOfflineTrust} from './offline-trust-rehearsal.mjs';
const hash=s=>createHash('sha256').update(s).digest('hex');
const raw='synthetic immutable snapshot bytes';
const key=hash('ephemeral-test-public-key');
const verification={status:'OBSERVED',signatureValid:true,snapshotMatches:true,verificationId:'test-only-123'};
const anchor={origin:'INDEPENDENT_OFFLINE_READONLY',keySha256:key,snapshotSha256:hash(raw)};
const snapshot={raw,verifiedSource:'INDEPENDENT_OFFLINE_READONLY'};
const args={verification,anchor,snapshot,seenIds:[],observedKeySha256:key};
test('offline simulation remains OBSERVED and cannot write ledger',()=>{const x=evaluateOfflineTrust(args);assert.equal(x.status,'OBSERVED');assert.equal(x.ledgerWrite,false);assert.equal(x.atomicReplayEnforced,false)});
test('missing anchor fails closed',()=>assert.equal(evaluateOfflineTrust({...args,anchor:null}).reason,'PROTECTED_ANCHOR_REQUIRED'));
test('wrong key pin fails closed',()=>assert.equal(evaluateOfflineTrust({...args,observedKeySha256:hash('forged')}).reason,'KEY_ANCHOR_MISMATCH'));
test('snapshot tampering fails closed',()=>assert.equal(evaluateOfflineTrust({...args,snapshot:{...snapshot,raw:'tampered'}}).reason,'SNAPSHOT_ANCHOR_MISMATCH'));
test('snapshot provenance required',()=>assert.equal(evaluateOfflineTrust({...args,snapshot:{...snapshot,verifiedSource:'WORKTREE'}}).reason,'INDEPENDENT_SNAPSHOT_REQUIRED'));
test('replay already observed fails closed',()=>assert.equal(evaluateOfflineTrust({...args,seenIds:[verification.verificationId]}).reason,'REPLAY_DETECTED'));
test('missing replay registry fails closed',()=>assert.equal(evaluateOfflineTrust({...args,seenIds:undefined}).reason,'REPLAY_REGISTRY_REQUIRED'));
test('invalid signature state fails closed',()=>assert.equal(evaluateOfflineTrust({...args,verification:{...verification,status:'UNVERIFIABLE'}}).reason,'SIGNATURE_NOT_OBSERVED'));
test('simulation does not mutate caller registry',()=>{const seen=[];evaluateOfflineTrust({...args,seenIds:seen});assert.deepEqual(seen,[])});
